source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PLTableViewController_Example' do
  pod 'PLTableManager', :path => '../'

  target 'PLTableViewController_Tests' do
    inherit! :search_paths

      pod 'Expecta'
  end
end
